apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: "5.8.73"
    helm:
      values: |
        controller:
          serviceType: LoadBalancer
          servicePort: 80
          servicePorts:
            - name: http
              port: 80
              targetPort: 8080
          admin:
            password: "admin123"
            
          podSecurityContext:
            enabled: true
            runAsUser: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
              
          containerSecurityContext:
            enabled: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  
            seccompProfile:
              type: RuntimeDefault
              
          image:
            tag: "2.516.1-jdk21"
            
          persistence:
            enabled: true
            existingClaim: "jenkins-data-pvc" 
            storageClass: "" 
            size: "8Gi"  
            accessMode: "ReadWriteOnce"

            
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

        # Fix sidecar resource limits to avoid policy violations
        controller:
          sidecars:
            configAutoReload:
              resources:
                requests:
                  cpu: "50m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"

        # Disable default storage class creation
        persistence:
          enabled: true
          existingClaim: "jenkins-data-pvc"

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true